[package]
name = "blob-nn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blob-engine = { path = "../blob-engine" }
serde = { workspace = true }
smallvec = { workspace = true }
tch = { version = "0.20", features = ["download-libtorch"] }
tracing = { workspace = true }

[dev-dependencies]
rand_xoshiro = { workspace = true }
