
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Smoke command from Session 9.1 — kept alive so the existing
 * `+page.svelte` button still has something to call.
 */
async engineVersion() : Promise<string> {
    return await TAURI_INVOKE("engine_version");
},
/**
 * Scan `checkpoints/` for `*.onnx` files. Sorted by modified-time, newest
 * first. The recents list is queried separately via [`list_recent_models`]
 * so the setup screen can render the two in distinct sections.
 */
async listModels() : Promise<Result<ModelInfo[], GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recently loaded models, most-recent first. Entries whose underlying
 * file is missing are silently dropped.
 */
async listRecentModels() : Promise<Result<ModelInfo[], GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recent_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load an ONNX model. Validates the file by constructing an
 * `OnnxEvaluator`; on success it's installed onto the active session
 * (if any) and the path is promoted to the head of the recents list.
 * 
 * Architecture metadata (`d_model`, `n_layers`, `n_heads`) is not derivable
 * from the public ONNX I/O contract — those dims live in initializer
 * shapes the `ort` crate doesn't surface. Returned as `None`; the setup
 * screen displays only the file size + modified time when they are.
 */
async loadModel(path: string) : Promise<Result<ModelInfo, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_model", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Promote `path` to the head of the recents list. Idempotent — calling
 * with the same path twice doesn't duplicate it.
 */
async addRecentModel(path: string) : Promise<Result<ModelInfo[], GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_recent_model", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize a fresh game from the setup screen and replace any prior
 * session. Returns the initial snapshot (Bidding phase, no hands dealt
 * to opponents — opponents stay empty until belief sampling).
 */
async newGame(config: GameConfig) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_game", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record the human's hand for the current round.
 * 
 * Validates count == `cards_dealt`, stores the bitmask on
 * `session.human_hand`, and writes through to `state.hands[human_seat]`.
 * Other seats remain empty — belief sampling will fill them at AI time.
 * Also seeds the engine RNG so opponents' "hands" can be drawn for
 * determinization later (Session 9.6).
 */
async setHumanHand(cards: number[]) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_human_hand", { cards }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submit the active player's bid. Wraps [`apply_bid`].
 */
async submitBid(seat: number, bid: number) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_bid", { seat, bid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a card played by `seat`. Public-state-only wrapper around
 * [`apply_play`].
 * 
 * For the human seat we hold the real hand and the engine's `legal_plays`
 * mask is authoritative. For opponents we don't know their hand at all —
 * we synthesize a one-card hand consisting of just the played card so
 * `apply_play` can run its trick bookkeeping uniformly. The card is
 * validated against public knowledge (not already played, not in the
 * human's hand, in range) before being recorded.
 */
async recordCardPlayed(seat: number, card: number) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_card_played", { seat, card }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run an AI suggestion on the current state.
 * 
 * Uses the loaded `OnnxEvaluator` if one is installed on the session,
 * otherwise falls back to `HeuristicEvaluator` so the AI surface stays
 * usable without a trained model. Per-card metrics are averaged across
 * `determinization_samples` belief samples; visit counts are summed.
 * 
 * Streaming `ai-thinking` progress events and a CancellationToken are
 * out of scope for this pass — the heuristic path completes well under
 * the 1.5 s budget and the on-NN path can be split into a tokio task in
 * a follow-up without touching the result shape.
 */
async requestAiSuggestion() : Promise<Result<AiSuggestion, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_ai_suggestion") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEngineSettings(settings: EngineSettings) : Promise<Result<null, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_engine_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pop the last event from the session log.
 * 
 * **Stub** — replay-from-checkpoint logic lands in Session 9.8. For now
 * the event is removed from the log but state is not rewound, so this
 * only signals "I tried to undo" to the frontend.
 */
async undoLastEvent() : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_last_event") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSession() : Promise<Result<string, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSession(path: string) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load persisted setup-screen form values from
 * `~/.blobmaster/settings.json`. Missing or corrupt files yield
 * [`AppSettings::default`] without erroring — first launch is the common
 * case.
 */
async loadAppSettings() : Promise<Result<AppSettings, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist setup-screen form values. Creates `~/.blobmaster/` on first
 * write.
 */
async saveAppSettings(settings: AppSettings) : Promise<Result<null, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Reply from `request_ai_suggestion`. Either bidding or playing.
 */
export type AiSuggestion = { phase: "bidding"; policy: number[]; recommended_bid: number; value_estimate: number } | { phase: "playing"; per_card: CardEval[]; recommended_card: number; value_estimate: number; sims_completed: number; depth: number }
/**
 * Form values persisted to `~/.blobmaster/settings.json` so the setup
 * screen survives across launches.
 * 
 * The players list is the single source of truth for seating: its length
 * is `num_players`, its order is play order, and the last entry is the
 * dealer. The "D" affordance in the UI re-orders the list so the chosen
 * dealer ends up at the bottom; the engine then computes first-to-play =
 * `(dealer + 1) % n` which is always seat 0 (the top row).
 */
export type AppSettings = { start_cards: number; trump_mode: TrumpMode; 
/**
 * 4..=7 entries. Position = seat index for the engine.
 */
players: PlayerConfig[]; engine_settings: EngineSettings; 
/**
 * Path of the most recently loaded model, if any. The setup screen
 * pre-selects it on launch (and silently ignores it if the file is
 * gone).
 */
last_model_path: string | null }
/**
 * Per-card eval annotation rendered on the bottom-left magnified hand and,
 * optionally, on the right CardGrid (Session 9.7).
 */
export type CardEval = { card: number; 
/**
 * Network policy ∈ [0, 1], renormalized over the legal subset.
 */
policy: number; 
/**
 * MCTS visits at the root child for this card. 0 if `mcts_simulations == 0`.
 */
mcts_visits: number; 
/**
 * MCTS Q-value ∈ [-1, 1] for the acting player.
 */
mcts_value: number; 
/**
 * Determinization-averaged win-rate ∈ [0, 1].
 */
win_rate: number }
export type CompletedTrick = { leader: number; winner: number; suit_led: number; 
/**
 * In play order, length == num_players.
 */
plays: TrickPlay[] }
/**
 * Engine-side knobs that change between calls but live for the session.
 */
export type EngineSettings = { 
/**
 * Softmax temperature applied to policy outputs (0.0–2.0). 1.0 = identity.
 */
temperature: number; 
/**
 * MCTS simulation budget. 0 = pure-policy mode (no tree).
 */
mcts_simulations: number; 
/**
 * Number of belief determinizations to average per AI suggestion.
 */
determinization_samples: number; 
/**
 * Optional fixed seed — `None` means time-seeded each call.
 */
deterministic_seed: number | null; 
/**
 * Display mode for inline AI eval (cycled by `E`).
 */
eval_display: EvalDisplay; 
/**
 * Render the primary eval annotation on the right CardGrid's legal
 * cells too (Session 9.7 secondary surface). Off by default to keep
 * the 52-cell grid uncluttered.
 */
show_grid_eval?: boolean }
export type EvalDisplay = "win-rate" | "policy" | "mcts-visits" | "value" | "off"
/**
 * Pre-game configuration (the form on `/setup`).
 */
export type GameConfig = { 
/**
 * 4..=7 in the GUI; engine accepts 3..=8.
 */
num_players: number; 
/**
 * Cards per player in the first round (`C` in plan-speak).
 */
start_cards: number; 
/**
 * Seat the human occupies. 0..num_players.
 */
human_seat: number; 
/**
 * Initial dealer seat. 0..num_players.
 */
dealer: number; 
/**
 * Per-seat display names. Length must equal `num_players`.
 */
player_names: string[]; 
/**
 * Trump policy. See [`TrumpMode`].
 */
trump_mode: TrumpMode }
/**
 * IPC mirror of `blob_engine::state::GamePhase`. Wrapped here so we can
 * derive `specta::Type` (the engine crate has no specta dependency).
 */
export type GamePhase = "bidding" | "playing" | "scoring" | "complete"
/**
 * Tagged error type crossing the bridge. `anyhow::Error` is intentionally
 * not used: the frontend needs to discriminate on `kind`.
 */
export type GuiError = { kind: "no-session" } | { kind: "invalid-config"; message: string } | { kind: "model-not-loaded" } | { kind: "model-load-failed"; message: string } | { kind: "illegal-action"; message: string } | { kind: "wrong-phase"; message: string } | { kind: "io"; message: string } | { kind: "session-not-found"; message: string } | { kind: "not-implemented"; message: string }
/**
 * Metadata about a discovered or loaded ONNX model file.
 * 
 * `d_model`, `n_layers`, `n_heads` are populated only after a successful
 * `load_model` call (read from the session's input shapes); discovery via
 * `list_models` leaves them `None`.
 */
export type ModelInfo = { path: string; file_name: string; size_bytes: number; 
/**
 * Last-modified time as a Unix epoch in seconds. `None` if the
 * filesystem doesn't expose it (rare on Windows/Linux/macOS).
 */
modified_unix_secs: number | null; d_model: number | null; n_layers: number | null; n_heads: number | null }
/**
 * One row of the players list. Order in `AppSettings.players` is play
 * order — the row at index 0 plays first in trick 1 and bids first; the
 * last row is implicitly the dealer (bids last, deals the next round).
 */
export type PlayerConfig = { name: string; 
/**
 * Exactly one row in the list has this set. Marks the human seat for
 * the GUI so AI suggestions and hand entry know which seat is yours.
 */
is_human: boolean }
/**
 * Frontend-facing view of a `GameSession`. Authoritative state lives in
 * Rust — this struct is rebuilt on every state-mutating command and the
 * frontend treats it as immutable for rendering.
 * 
 * Bid/play masks (`legal_bids`, `legal_plays`) are pre-flattened to
 * card/bid index lists. They are populated only when the **human** is the
 * active player; for opponent turns the frontend shouldn't be making play
 * suggestions anyway, and the engine validates legality on submission.
 */
export type SessionSnapshot = { phase: GamePhase; num_players: number; cards_dealt: number; start_cards: number; round_idx: number; 
/**
 * Total rounds in this game (derived from `start_cards` + `num_players`).
 */
total_rounds: number; trump_suit: number; dealer: number; current_player: number; trick_leader: number; 
/**
 * `bids[i] = Some(b)` once seat `i` has bid this round, else `None`.
 */
bids: (number | null)[]; tricks_won: number[]; cumulative_scores: number[]; player_names: string[]; human_seat: number; 
/**
 * Card indices currently in the human's hand (sorted ascending).
 */
human_hand: number[]; trick_in_progress: TrickPlay[]; 
/**
 * Completed tricks for the **current round only**.
 */
trick_history: CompletedTrick[]; legal_bids: number[] | null; legal_plays: number[] | null; 
/**
 * Dealer's forbidden bid value when currently at the dealer's turn,
 * per [`blob_engine::bidding::forbidden_bid`].
 */
forbidden_bid: number | null; event_log_len: number; model_loaded: boolean }
export type TrickPlay = { seat: number; card: number }
/**
 * Trump policy for the game. `AutoRotate` follows
 * [`blob_engine::round::trump_for_round`] (the engine's default cycle);
 * the four fixed-suit variants and `NoTrump` are surfaced for completeness
 * but require an engine extension to take effect — for Session 9.2 they are
 * accepted by `new_game` and recorded on the session, but the engine
 * continues to use auto-rotate. Wiring the override is a follow-up.
 */
export type TrumpMode = "auto-rotate" | "spades" | "hearts" | "clubs" | "diamonds" | "no-trump"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
