
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Smoke command from Session 9.1 — kept alive so the existing
 * `+page.svelte` button still has something to call.
 */
async engineVersion() : Promise<string> {
    return await TAURI_INVOKE("engine_version");
},
/**
 * Scan `checkpoints/` for `*.onnx` files plus the recents list.
 * 
 * Stub: just enumerates files in the workspace `checkpoints/` directory.
 * The recents-list integration lands in Session 9.3.
 */
async listModels() : Promise<Result<ModelInfo[], GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load an ONNX model into the active session.
 * 
 * `OnnxEvaluator::from_file` does the real work; on success the session's
 * `evaluator` slot is populated and subsequent `request_ai_suggestion`
 * calls have a model to use. If no session exists yet, the load still
 * happens and the model is dropped — the next `new_game` will need to
 * reload. (Session 9.3 will refactor this so the model lives outside the
 * session.)
 */
async loadModel(path: string) : Promise<Result<ModelInfo, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_model", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize a fresh game from the setup screen and replace any prior
 * session. Returns the initial snapshot (Bidding phase, no hands dealt
 * to opponents — opponents stay empty until belief sampling).
 */
async newGame(config: GameConfig) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_game", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record the human's hand for the current round.
 * 
 * Validates count == `cards_dealt`, stores the bitmask on
 * `session.human_hand`, and writes through to `state.hands[human_seat]`.
 * Other seats remain empty — belief sampling will fill them at AI time.
 * Also seeds the engine RNG so opponents' "hands" can be drawn for
 * determinization later (Session 9.6).
 */
async setHumanHand(cards: number[]) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_human_hand", { cards }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submit the active player's bid. Wraps [`apply_bid`].
 */
async submitBid(seat: number, bid: number) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_bid", { seat, bid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a card played by `seat`. Public-state-only wrapper around
 * [`apply_play`].
 * 
 * **Stub** — the public-state-only variant of `apply_play` lands in
 * Session 9.6. For now this surfaces a structured `NotImplemented` error
 * so the frontend can wire the call site without crashing.
 */
async recordCardPlayed(seat: number, card: number) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_card_played", { seat, card }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run an AI suggestion on the current state.
 * 
 * **Stub** — returns a deterministic mock payload so the frontend can
 * render the eval surface end-to-end. Real MCTS + belief wiring lands in
 * Session 9.7.
 */
async requestAiSuggestion() : Promise<Result<AiSuggestion, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_ai_suggestion") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEngineSettings(settings: EngineSettings) : Promise<Result<null, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_engine_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pop the last event from the session log.
 * 
 * **Stub** — replay-from-checkpoint logic lands in Session 9.8. For now
 * the event is removed from the log but state is not rewound, so this
 * only signals "I tried to undo" to the frontend.
 */
async undoLastEvent() : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_last_event") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSession() : Promise<Result<string, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSession(path: string) : Promise<Result<SessionSnapshot, GuiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Reply from `request_ai_suggestion`. Either bidding or playing.
 */
export type AiSuggestion = { phase: "bidding"; policy: number[]; recommended_bid: number; value_estimate: number } | { phase: "playing"; per_card: CardEval[]; recommended_card: number; value_estimate: number; sims_completed: number; depth: number }
/**
 * Per-card eval annotation rendered on the bottom-left magnified hand and,
 * optionally, on the right CardGrid (Session 9.7).
 */
export type CardEval = { card: number; 
/**
 * Network policy ∈ [0, 1], renormalized over the legal subset.
 */
policy: number; 
/**
 * MCTS visits at the root child for this card. 0 if `mcts_simulations == 0`.
 */
mcts_visits: number; 
/**
 * MCTS Q-value ∈ [-1, 1] for the acting player.
 */
mcts_value: number; 
/**
 * Determinization-averaged win-rate ∈ [0, 1].
 */
win_rate: number }
export type CompletedTrick = { leader: number; winner: number; suit_led: number; 
/**
 * In play order, length == num_players.
 */
plays: TrickPlay[] }
/**
 * Engine-side knobs that change between calls but live for the session.
 */
export type EngineSettings = { 
/**
 * Softmax temperature applied to policy outputs (0.0–2.0). 1.0 = identity.
 */
temperature: number; 
/**
 * MCTS simulation budget. 0 = pure-policy mode (no tree).
 */
mcts_simulations: number; 
/**
 * Number of belief determinizations to average per AI suggestion.
 */
determinization_samples: number; 
/**
 * Optional fixed seed — `None` means time-seeded each call.
 */
deterministic_seed: number | null; 
/**
 * Display mode for inline AI eval (cycled by `E`).
 */
eval_display: EvalDisplay }
export type EvalDisplay = "win-rate" | "policy" | "mcts-visits" | "value" | "off"
/**
 * Pre-game configuration (the form on `/setup`).
 */
export type GameConfig = { 
/**
 * 4..=7 in the GUI; engine accepts 3..=8.
 */
num_players: number; 
/**
 * Cards per player in the first round (`C` in plan-speak).
 */
start_cards: number; 
/**
 * Seat the human occupies. 0..num_players.
 */
human_seat: number; 
/**
 * Initial dealer seat. 0..num_players.
 */
dealer: number; 
/**
 * Per-seat display names. Length must equal `num_players`.
 */
player_names: string[]; 
/**
 * Trump policy. See [`TrumpMode`].
 */
trump_mode: TrumpMode }
/**
 * IPC mirror of `blob_engine::state::GamePhase`. Wrapped here so we can
 * derive `specta::Type` (the engine crate has no specta dependency).
 */
export type GamePhase = "bidding" | "playing" | "scoring" | "complete"
/**
 * Tagged error type crossing the bridge. `anyhow::Error` is intentionally
 * not used: the frontend needs to discriminate on `kind`.
 */
export type GuiError = { kind: "no-session" } | { kind: "invalid-config"; message: string } | { kind: "model-not-loaded" } | { kind: "model-load-failed"; message: string } | { kind: "illegal-action"; message: string } | { kind: "wrong-phase"; message: string } | { kind: "io"; message: string } | { kind: "session-not-found"; message: string } | { kind: "not-implemented"; message: string }
/**
 * Metadata about a discovered or loaded ONNX model file.
 * 
 * `d_model`, `n_layers`, `n_heads` are populated only after a successful
 * `load_model` call (read from the session's input shapes); discovery via
 * `list_models` leaves them `None`.
 */
export type ModelInfo = { path: string; file_name: string; size_bytes: number; 
/**
 * Last-modified time as a Unix epoch in seconds. `None` if the
 * filesystem doesn't expose it (rare on Windows/Linux/macOS).
 */
modified_unix_secs: number | null; d_model: number | null; n_layers: number | null; n_heads: number | null }
/**
 * Frontend-facing view of a `GameSession`. Authoritative state lives in
 * Rust — this struct is rebuilt on every state-mutating command and the
 * frontend treats it as immutable for rendering.
 * 
 * Bid/play masks (`legal_bids`, `legal_plays`) are pre-flattened to
 * card/bid index lists. They are populated only when the **human** is the
 * active player; for opponent turns the frontend shouldn't be making play
 * suggestions anyway, and the engine validates legality on submission.
 */
export type SessionSnapshot = { phase: GamePhase; num_players: number; cards_dealt: number; start_cards: number; round_idx: number; 
/**
 * Total rounds in this game (derived from `start_cards` + `num_players`).
 */
total_rounds: number; trump_suit: number; dealer: number; current_player: number; trick_leader: number; 
/**
 * `bids[i] = Some(b)` once seat `i` has bid this round, else `None`.
 */
bids: (number | null)[]; tricks_won: number[]; cumulative_scores: number[]; player_names: string[]; human_seat: number; 
/**
 * Card indices currently in the human's hand (sorted ascending).
 */
human_hand: number[]; trick_in_progress: TrickPlay[]; 
/**
 * Completed tricks for the **current round only**.
 */
trick_history: CompletedTrick[]; legal_bids: number[] | null; legal_plays: number[] | null; 
/**
 * Dealer's forbidden bid value when currently at the dealer's turn,
 * per [`blob_engine::bidding::forbidden_bid`].
 */
forbidden_bid: number | null; event_log_len: number; model_loaded: boolean }
export type TrickPlay = { seat: number; card: number }
/**
 * Trump policy for the game. `AutoRotate` follows
 * [`blob_engine::round::trump_for_round`] (the engine's default cycle);
 * the four fixed-suit variants and `NoTrump` are surfaced for completeness
 * but require an engine extension to take effect — for Session 9.2 they are
 * accepted by `new_game` and recorded on the session, but the engine
 * continues to use auto-rotate. Wiring the override is a follow-up.
 */
export type TrumpMode = "auto-rotate" | "spades" | "hearts" | "clubs" | "diamonds" | "no-trump"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
